### ISSUE TITLE
easy run

### ISSUE THREAD

**Issue by boterhammen** [RoyPlu/Flare#2]
Not everyone likes / knows Angular.

Could you add a simple setup script or something that uses an angular container?
e.g. something like this:

docker run -it --rm -w /app -v $(pwd)/my-project-name:/app -p 4200:4200 alexsuch/angular-cli:7.0.6-chromium ng serve --host 0.0.0.0

**Comment by RoyPlu** [comment]
@boterhammen The instructions on how to start up the project are on the bottom of the README for anyone who needs it. I plan to keep just the Angular project on here, you can do what you want with it. I'm not sure if your solution is any simpler/better though.
