### ISSUE TITLE
The build command requires to be run in an Angular project, but a project definition could not be found.

### ISSUE THREAD

**Issue by kgorinson** [RoyPlu/Flare#3]
All of your ng commands fail with the error
`The build command requires to be run in an Angular project, but a project definition could not be found.
`
This seems to maybe be because there is no angular.json. Not sure.

**Comment by RoyPlu** [comment]
@kgor93 You might have a stray (hidden) .angular.json file somewhere up your folder tree that's causing this problem

**Comment by kgorinson** [comment]
Nope it's a fresh build. No hidden files. Deleted it and tried again. I think it's missing something.

**Comment by RoyPlu** [comment]
If you've recently updated your Angular CLI this makes the .angular-cli.json file redundant it seems, This project is still running on an older version of Angular.

Try running the following command, it will make the conversion to a .angular.json file for you:

ng update @angular/cli --migrate-only --from=1.6.6

**Comment by kgorinson** [comment]
What worked was downgrading to 1.6.6
